@startuml
skinparam nodesep 200
skinparam ranksep 200
skinparam defaultFontSize 18

skinparam linetype ortho

hide empty members
!theme blueprint

entity "API Key" as api_key {
    API-ID <<CK>>
    API-Key
    Created-At
}

entity "Build Team" as build_team {
    Build-Team-ID <<CK>>
}

entity "Country" as country {
    Country-Code <<CK>>
    Continent
}

entity "City Project" as city_project {
    City-Project-ID <<CK>>
    Is-Visible
}

entity "Builder" as builder {
    UUID <<CK>>
    Name
    Score
}

entity "Builder Setting" as builder_setting {
    Plot-Type
}

entity "Plot Difficulty" as plot_difficulty {
    Difficulty-ID <<CK>>
    Multiplier
    Score-Requirement
}

entity "Plot" as plot {
    Plot-ID <<CK>>
    Status
    Score
    Last-Activity-At
    Outline-Bounds
    Outline-Schematic
    Environment-Schematic
    Complete-Schematic
    Created-By
    Created-At
}

entity "Plot Tutorial" as plot_tutorial {
    Plot-Tutorial-ID <<CK>>
    Stage-ID
    Is-Complete
    First-Stage-Started-At
    Last-Stage-Completed-At
}

api_key "assigned to \n1" -- "belongs to \n0..1" build_team

build_team "belongs to \n0..*" *-- "assigned to \n0..*" country
build_team "assigned to \n0..*" -- "has 0..* reviewers" builder

country "has \n1" *-- "assigned to \n0..*" city_project

builder "has 1 plot creator" -- "is in \n0..*" plot
builder "assigned to \n1" *--- "has 1" builder_setting

plot "assigned to 0..*" -- "built by \n0..*" builder
(builder, plot) -- "Slot"

plot "assigned to \n0..*" --* "in 1" city_project
plot "assigned to \n0..*" --* "has 1" plot_difficulty

plot_tutorial "has \n1" --* "belongs to \n1" builder
@enduml