@startuml
skinparam nodesep 100
skinparam ranksep 250
skinparam defaultFontSize 18

skinparam linetype ortho

hide circle
hide empty members
!theme blueprint

entity system_info {
    system_id <<PK>>
    db_version
    current_plot_version
    last_update
    description
}

entity build_team {
    build_team_id <<PK>>
    name
    api_key
    api_create_date
}

entity server {
    build_team_id <<PK>>
    server_name <<FK>>
}

entity country {
    country_code <<PK>>
    continent
    material
    custom_model_data
}

entity city_project {
    city_project_id <<PK>>
    country_code <<FK>>
    server_name <<FK>>
    is_visible
}

entity builder {
    uuid <<PK>>
    name
    score
    first_slot
    second_slot
    third_slot
    plot_type
}

entity plot_difficulty {
    difficulty_id <<PK>>
    multiplier
    score_requirement
}

entity plot {
    plot_id <<PK>>
    city_project_id <<FK>>
    difficulty_id <<FK>>
    status
    score
    outline_bounds
    initial_schematic
    complete_schematic
    last_activity_date
    is_pasted
    mc_version
    plot_version
    created_by
    create_date
}

entity tutorial {
    tutorial_id <<PK>>
    uuid <<PK>>
    stage_id
    is_complete
    first_stage_start_date
    last_stage_complete_date
}

entity plot_review {
    review_id <<PK>>
    plot_id <<FK>>
    rating
    feedback
    reviewed_by
    review_date
}

entity build_team_has_country {
    build_team_id <<PK>>
    country_code <<PK>>
}

entity build_team_has_city_project {
    build_team_id <<PK>>
    city_project_id <<PK>>
}

entity build_team_has_reviewer {
    build_team_id <<PK>>
    uuid <<PK>>
}

entity builder_has_review_notification {
    review_id <<PK>>
    uuid <<PK>>
}

entity builder_has_plot {
    plot_id <<PK>>
    uuid <<PK>>
    is_owner
}

build_team "1" <-- "0..*" build_team_has_city_project
build_team "1" <-- "0..*" build_team_has_country
build_team "1" <-- "0..*" build_team_has_reviewer
build_team "1" <-- "0..*" server

country "1" <--- "0..*" city_project
country "1" <--- "0..*" build_team_has_country

city_project "1" <-- "0..*" build_team_has_city_project
city_project "0..*" --> "1" server

plot_review "1" <-- "0..*" builder_has_review_notification
plot_review "0..*" --> "1" plot

builder "1" <-- "0..*" build_team_has_reviewer
builder "1" <--- "1" tutorial
builder "1" <-- "0..*" builder_has_review_notification
builder "1" <-- "0..*" builder_has_plot

plot "0..*" --> "1" city_project
plot "0..*" ---> "1" plot_difficulty
plot "1" <-- "0..*" builder_has_plot
@enduml